name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: "korczak-xyz/yarn.lock"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: korczak-xyz
      - name: Build
        run: yarn build
        working-directory: korczak-xyz
      - name: Test
        run: yarn test
        working-directory: korczak-xyz
